publish.unittestresults.ParsedUnitTestResults(
  files=1,
  errors=[],
  suites=1,
  suite_tests=6,
  suite_skipped=1,
  suite_failures=3,
  suite_errors=0,
  suite_time=0,
  suite_details=[
    publish.unittestresults.UnitTestSuite(
      name='MSTestSuite',
      tests=6,
      skipped=1,
      failures=3,
      errors=0,
      stdout=None,
      stderr=None
    )
  ],
  cases=[
    publish.unittestresults.UnitTestCase(
      result_file='nunit/NUnit-net461-sample.trx',
      test_file=None,
      line=None,
      class_name='SampleProject.NUnit.TestServiceTests',
      test_name='TestTheory(False)',
      result='failure',
      message='  Expected: False\r\n  But was:  True\r\n',
      content='  Expected: False\r\n  But was:  True\r\n   at '
        'SampleProject.NUnit.TestServiceTests.TestTheory(Boolean expected) in '
        'C:\\Dev\\LiquidTestReports\\test\\SampleProject\\SampleProject.Tests.NUnit'
        '\\TestServiceTests.cs:line 25\r\n',
      stdout=None,
      stderr=None,
      time=0.002
    ),
    publish.unittestresults.UnitTestCase(
      result_file='nunit/NUnit-net461-sample.trx',
      test_file=None,
      line=None,
      class_name='SampleProject.NUnit.TestServiceTests',
      test_name='SkipTest',
      result='skipped',
      message='Ignore test',
      content='Ignore test',
      stdout=None,
      stderr=None,
      time=0.0
    ),
    publish.unittestresults.UnitTestCase(
      result_file='nunit/NUnit-net461-sample.trx',
      test_file=None,
      line=None,
      class_name='SampleProject.NUnit.TestServiceTests',
      test_name='TestTheory(True)',
      result='success',
      message=None,
      content=None,
      stdout=None,
      stderr=None,
      time=0.018
    ),
    publish.unittestresults.UnitTestCase(
      result_file='nunit/NUnit-net461-sample.trx',
      test_file=None,
      line=None,
      class_name='SampleProject.NUnit.TestServiceTests',
      test_name='TestThrowingException',
      result='failure',
      message='System.Exception : Pretty good exception',
      content='System.Exception : Pretty good exception   at '
        'SampleProject.TestService.GetException() in '
        'C:\\Dev\\LiquidTestReports\\test\\SampleProject\\SampleProject\\TestService'
        '.cs:line 19\r\n   at '
        'SampleProject.NUnit.TestServiceTests.TestThrowingException() in '
        'C:\\Dev\\LiquidTestReports\\test\\SampleProject\\SampleProject.Tests.NUnit'
        '\\TestServiceTests.cs:line 50',
      stdout=None,
      stderr=None,
      time=0.005
    ),
    publish.unittestresults.UnitTestCase(
      result_file='nunit/NUnit-net461-sample.trx',
      test_file=None,
      line=None,
      class_name='SampleProject.NUnit.TestServiceTests',
      test_name='FailTest',
      result='failure',
      message='  Expected: True\r\n  But was:  False\r\n',
      content='  Expected: True\r\n  But was:  False\r\n   at '
        'SampleProject.NUnit.TestServiceTests.FailTest() in '
        'C:\\Dev\\LiquidTestReports\\test\\SampleProject\\SampleProject.Tests.NUnit'
        '\\TestServiceTests.cs:line 61\r\n',
      stdout=None,
      stderr=None,
      time=0.111
    ),
    publish.unittestresults.UnitTestCase(
      result_file='nunit/NUnit-net461-sample.trx',
      test_file=None,
      line=None,
      class_name='SampleProject.NUnit.TestServiceTests',
      test_name='PassingTest',
      result='success',
      message=None,
      content=None,
      stdout=None,
      stderr=None,
      time=0.002
    )
  ]
)